Added extra errors

diff --git a/rsnapshot-backup-dns b/rsnapshot-backup-dns
--- a/rsnapshot-backup-dns
+++ b/rsnapshot-backup-dns
@@ -57,10 +57,16 @@ elif [ "$1" == "" ]; then
 else
 	DOMAIN=$1;
 
-	if [ "$2" != "" ]; then
-		PRIMARY_NS=$2;
-	else
+	if [ -z "$2" ]; then
 		PRIMARY_NS=$($DIG +short soa $DOMAIN | $AWK '{ print $1; }');
+
+		if [ -z "$PRIMARY_NS" ]; then
+			echo -n "Unable to fetch SOA from your DNS server, you can specify ";
+			echo "the primary DNS server manually see $0 --help";
+			exit 3;
+		fi
+	else
+		PRIMARY_NS=$2;
 	fi
 fi
 
@@ -69,9 +75,9 @@ echo -e ";\n; $DOMAIN from $PRIMARY_NS\n;\n" > "$DOMAIN.zone";
 
 echo "; -- BEGIN DATA --" >> "$DOMAIN.zone";
 $DIG +noall +answer axfr $DOMAIN @$PRIMARY_NS >> "$DOMAIN.zone" || ( 
- $RM -f "$DOMAIN.zone";
- echo "Unable to perform AXFR request from $PRIMARY_NS";
- exit 2;
+	$RM -f "$DOMAIN.zone";
+	echo "Unable to perform AXFR request from $PRIMARY_NS";
+	exit 2;
 );
 echo "; -- END DATA --" >> "$DOMAIN.zone";
 
