If the AXFR request fails print a message, remove the zone file and die

diff --git a/rsnapshot-backup-dns b/rsnapshot-backup-dns
--- a/rsnapshot-backup-dns
+++ b/rsnapshot-backup-dns
@@ -18,9 +18,11 @@ WHICH=$(which which);
 if [ "$?" != "0" ]; then
 	AWK=/usr/bin/awk;
 	DIG=/usr/bin/dig;
+	RM=/bin/rm;
 else
 	AWK=$($WHICH awk);
 	DIG=$($WHICH dig);
+	RM=$($WHICH rm);
 fi
 
 function show_usage {
@@ -61,7 +63,11 @@ PRIMARY_NS=$($DIG +short soa $DOMAIN @80.225.250.186 | $AWK '{ print $1; }');
 echo -e ";\n; $DOMAIN from $PRIMARY_NS\n;\n" > "$DOMAIN.zone";
 
 echo "; -- BEGIN DATA --" >> "$DOMAIN.zone";
-$DIG +noall +answer axfr $DOMAIN @$PRIMARY_NS >> "$DOMAIN.zone";
+$DIG +noall +answer axfr $DOMAIN @$PRIMARY_NS >> "$DOMAIN.zone" || ( 
+ $RM -f "$DOMAIN.zone";
+ echo "Unable to perform AXFR request from $PRIMARY_NS";
+ exit 2;
+);
 echo "; -- END DATA --" >> "$DOMAIN.zone";
 
 exit $?;
