Release 1.0.2

diff --git a/rsnapshot-backup-dns b/rsnapshot-backup-dns
--- a/rsnapshot-backup-dns
+++ b/rsnapshot-backup-dns
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# rsnapshot-backup-dpkg
+# rsnapshot-backup-dns
 #
 # (c) Copyright 2007 Chris Smith
 # This is free software. You may redistribute copies of it under the terms of
@@ -16,20 +16,24 @@
 WHICH=$(which which);
 
 if [ "$?" != "0" ]; then
-	DPKG=/usr/bin/dpkg
+	AWK=/usr/bin/awk;
+	DIG=/usr/bin/dig;
+	RM=/bin/rm;
 else
-	DPKG=$($WHICH dpkg);
+	AWK=$($WHICH awk);
+	DIG=$($WHICH dig);
+	RM=$($WHICH rm);
 fi
 
 function show_usage {
-	echo "Usage: $0 [ --version | --help ]";
+	echo "Usage: $0 [ --version | --help | domain ]";
 	echo -e "    --help\tDisplay this help and exit";
 	echo -e "    --version\tDisplay version and exit";
 	exit $1;
 }
 
 function show_version {
-	echo "rsnapshot-backup-dpkg";
+	echo "rsnapshot-backup-dns";
 	echo '$Id$';
 	echo ""
 	echo "(c) Copyright 2007 Chris Smith";
@@ -42,13 +46,28 @@ function show_version {
 }
 
 if [ "$1" == "--help" ]; then
-	show_usage 0
+	show_usage 0;
 	exit 0;
 elif [ "$1" == "--version" ]; then
-	show_version
+	show_version;
 	exit 0;
+elif [ "$1" == "" ]; then
+	show_usage 1;
+	exit 1;
+else
+	DOMAIN=$1;
 fi
 
-$DPKG --get-selections > dpkg-status
+PRIMARY_NS=$($DIG +short soa $DOMAIN @80.225.250.186 | $AWK '{ print $1; }');
 
-exit $?
+echo -e ";\n; $DOMAIN from $PRIMARY_NS\n;\n" > "$DOMAIN.zone";
+
+echo "; -- BEGIN DATA --" >> "$DOMAIN.zone";
+$DIG +noall +answer axfr $DOMAIN @$PRIMARY_NS >> "$DOMAIN.zone" || ( 
+ $RM -f "$DOMAIN.zone";
+ echo "Unable to perform AXFR request from $PRIMARY_NS";
+ exit 2;
+);
+echo "; -- END DATA --" >> "$DOMAIN.zone";
+
+exit $?;
