Secuirty changes mostly

diff --git a/rsnapshot-backup-dns b/rsnapshot-backup-dns
--- a/rsnapshot-backup-dns
+++ b/rsnapshot-backup-dns
@@ -17,12 +17,16 @@ WHICH=$(which which);
 
 if [ "$?" != "0" ]; then
 	AWK=/usr/bin/awk;
+	CHMOD=/bin/chmod;
 	DIG=/usr/bin/dig;
 	RM=/bin/rm;
+	TOUCH=/usr/bin/touch;
 else
 	AWK=$($WHICH awk);
+	CHMOD=$($WHICH chmod);
 	DIG=$($WHICH dig);
 	RM=$($WHICH rm);
+	TOUCH=$($WHICH touch);
 fi
 
 function show_usage {
@@ -70,6 +74,15 @@ else
 	fi
 fi
 
+if [ -f "$DOMAIN.zone" ]; then
+	echo "Zone file [$DOMAIN.zone] already exists!";
+	exit 4;
+fi
+
+$TOUCH "$DOMAIN.zone" 2>/dev/null || echo "Failed to create zone file!"; \
+exit 5;
+
+$CHMOD 0600 "$DOMAIN.zone";
 
 echo -e ";\n; $DOMAIN from $PRIMARY_NS\n;\n" > "$DOMAIN.zone";
 
diff --git a/rsnapshot-backup-dpkg b/rsnapshot-backup-dpkg
--- a/rsnapshot-backup-dpkg
+++ b/rsnapshot-backup-dpkg
@@ -16,9 +16,13 @@
 WHICH=$(which which);
 
 if [ "$?" != "0" ]; then
-	DPKG=/usr/bin/dpkg
+	CHMOD=/bin/chmod;
+	DPKG=/usr/bin/dpkg;
+	TOUCH=/usr/bin/touch;
 else
+	CHMOD=$($WHICH chmod);
 	DPKG=$($WHICH dpkg);
+	TOUCH=$($WHICH touch);
 fi
 
 function show_usage {
@@ -49,6 +53,13 @@ elif [ "$1" == "--version" ]; then
 	exit 0;
 fi
 
-$DPKG --get-selections > dpkg-status
+STATUS_FILE="dpkg-status";
+
+$TOUCH "$STATUS_FILE" 2>/dev/null || echo "Failed to create status file!"; \
+exit 2;
+
+$CHMOD 0600 "STATUS_FILE";
+
+$DPKG --get-selections > "$STATUS_FILE"
 
 exit $?
diff --git a/rsnapshot-backup-mysql b/rsnapshot-backup-mysql
--- a/rsnapshot-backup-mysql
+++ b/rsnapshot-backup-mysql
@@ -16,15 +16,19 @@
 WHICH=$(which which);
 
 if [ "$?" != "0" ]; then
-	GZIP=/bin/gzip
-	MYSQL=/usr/bin/mysql
-	MYSQLDUMP=/usr/bin/mysqldump
-	XARGS=/usr/bin/xargs
+	CHMOD=/bin/chmod;
+	GZIP=/bin/gzip;
+	MYSQL=/usr/bin/mysql;
+	MYSQLDUMP=/usr/bin/mysqldump;
+	XARGS=/usr/bin/xargs;
+	TOUCH=/usr/bin/touch;
 else
+	CHMOD=$($WHICH chmod);
 	GZIP=$($WHICH gzip);
 	MYSQL=$($WHICH mysql);
 	MYSQLDUMP=$($WHICH mysqldump);
 	XARGS=$($WHICH xargs);
+	TOUCH=$($WHICH touch);
 fi
 
 function show_usage {
@@ -67,6 +71,12 @@ fi
 
 for DB in `ls_db`; do
 	echo "Backing up $DB...";
+
+	$TOUCH "$DB.sql.gz" 2>/dev/null || echo "Failed to create dump file!"; \
+	exit 2;
+
+	$CHMOD 0600 "$DOMAIN.zone";
+
 	# The likely hood that dumps will be the same is slim,
 	# mysqldump puts a timestamp in the file, so I figured
 	# it would be better to compress the output.
